In [1]:
import numpy as np

In [3]:
from abc import ABC, abstractmethod

class Model(ABC):
    def __init__(self, random_state=None):
        self.random_state = random_state


    @abstractmethod
    def fit(self, X, y, warm_start=False):
        pass

    @abstractmethod
    def predict(self):
        pass

In [73]:
import numpy as np

class LinearRegressor(Model):
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X, y):
        if X.shape[0] != y.shape[0]:
            raise Exception(
                """
                Number of rows in X doesn't match shape of y
                """
                            )

        if len(X.shape) != 2:
            raise Exception(
                """
                    X must be a 2-dimensional array
                """
            )

        X = np.concat([X, np.ones(X.shape[0]).reshape([-1, 1])], axis=1)
        solution = np.linalg.pinv(X.T @ X) @ X.T @ y.reshape([-1, 1])
        self.coef_ = solution[:-1].reshape([-1, 1])
        self.intercept_ = solution[-1]

    def predict(self, X):
        return  X @ self.coef_ + self.intercept_

In [79]:
X = np.random.rand(100, 2) * 100
y = X[:, 0] + X[:, 1]
X = X + np.random.rand(100, 2)

In [80]:
model = LinearRegressor()

In [81]:
model.fit(X, y)

In [82]:
model.predict(X)

array([[154.15599034],
       [ 56.58470061],
       [ 73.52489302],
       [ 95.07692806],
       [139.09407376],
       [ 22.23111268],
       [ 96.8424981 ],
       [ 65.07742515],
       [ 58.99706026],
       [ 26.70170216],
       [144.04135465],
       [144.88889401],
       [ 97.68098392],
       [ 95.35780005],
       [137.48851476],
       [172.08193972],
       [ 63.55048608],
       [100.7737042 ],
       [180.16400161],
       [130.57658504],
       [ 93.99715879],
       [164.2610106 ],
       [ 79.34750358],
       [153.14605861],
       [166.32283213],
       [164.9858416 ],
       [ 86.32665734],
       [112.86427679],
       [125.72961431],
       [142.49258114],
       [ 35.39800147],
       [158.47341773],
       [ 96.82032544],
       [148.87833669],
       [158.40894727],
       [ 79.00433478],
       [ 41.84657916],
       [ 89.70568037],
       [184.16232663],
       [ 73.53634572],
       [142.64653182],
       [ 91.9576309 ],
       [155.30450183],
       [104

In [83]:
model.coef_

array([[0.99742506],
       [1.002002  ]])

In [87]:
model.predict(X).reshape([1, -1]) - y

array([[-3.33087430e-02,  1.44938920e-01, -2.12647082e-01,
         7.94978952e-02, -3.55540649e-01,  1.26956988e-02,
        -4.88938265e-01,  2.11610018e-01, -1.74045767e-02,
         2.64198256e-01, -2.10933764e-01, -4.46312002e-04,
         1.67327850e-01,  8.37018363e-01, -4.58808688e-02,
        -1.09591405e-01, -3.70664246e-01,  7.49293933e-02,
        -1.12429815e-01, -7.98526624e-01, -3.97098821e-01,
        -5.79277575e-01,  5.63382149e-01,  1.16180099e-01,
        -3.59695023e-03, -1.55486439e-02, -2.00276091e-01,
         5.19564819e-01,  6.26132871e-01,  9.68400871e-01,
         4.42529497e-01, -1.03759757e-01, -1.52846291e-01,
         3.90096529e-01,  2.67571459e-01,  1.83387137e-02,
         1.06584901e-01, -3.98582310e-01, -3.35783109e-02,
        -1.69956292e-01, -1.68642756e-01, -3.06813217e-01,
        -3.46469399e-01, -6.57401144e-01, -8.72127366e-02,
        -5.97990677e-02,  9.36014510e-02, -6.95235732e-01,
         8.23625023e-01,  1.89304278e-01, -1.14941539e-0

In [90]:
np.power(model.predict(X).reshape([1, -1]) - y, 2).mean()

np.float64(0.1329671642374704)

In [61]:
solution = np.linalg.pinv(X.T @ X) @ X.T @ y.reshape([-1, 1])

In [62]:
coef_ = solution[:-1]
intercept_ = solution[-1]

In [63]:
coef_

array([[0.4],
       [0.2]])

In [64]:
X = X[:, :-1]

In [65]:
X @ coef_ + intercept_

array([[1.],
       [2.]])

In [66]:
intercept_

array([2.66453526e-15])